package addcontent;

import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class deleteSymptom extends javax.swing.JFrame {

    DefaultComboBoxModel combomodel = new DefaultComboBoxModel();
    DbConnect dbcon = new DbConnect();
    DbConnect dbcon2 = new DbConnect();
    DbConnect dbcon3 = new DbConnect();
    DbConnect dbcon4 = new DbConnect();
    Vector<String> combo1;
    Vector<String> combo2;
    Vector<String> combo3;
    Vector<String> combo4;
    Vector<String> combo5;
     Vector<String> combo6;
     Vector<String> combo7;
    static int i = 0;

    public deleteSymptom() {
        initComponents();
        loadCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jButton10 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(487, 547));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jLabel9.setText("symptoms");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, -1));

        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, 80));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("sub level1");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, -1));

        jButton2.setText("delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 270, 80));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("param");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 40));

        jButton8.setText("delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 80, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 290, 40));

        jButton3.setText("refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 110, 40));

        jButton11.setText("back");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 80, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 640, 60));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("sub_level2");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, -1));

        jButton4.setText("delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, 80));

        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jPanel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jLabel7.setText("sub_level4");
        jPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel11.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, -1));

        jButton6.setText("delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 80, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 270, 80));

        jPanel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jPanel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jLabel8.setText("sub_level5");
        jPanel15.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel15.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, -1));

        jButton7.setText("delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 270, 80));

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jLabel6.setText("sub_level3");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, -1));

        jButton5.setText("delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 80, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 270, 80));

        jPanel23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jPanel25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jPanel23.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jLabel11.setText("sub_level4");
        jPanel23.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel23.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, -1));

        jButton10.setText("delete");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel23.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 80, -1));

        jPanel1.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 270, 80));

        jPanel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jPanel21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jPanel19.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 110, 80));

        jLabel10.setText("illness");
        jPanel19.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel19.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, -1));

        jButton9.setText("delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 270, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
        
        
         try {
              dbcon.rs = dbcon.st.executeQuery("select id from symptoms_sub where sym_id='" + combo1.elementAt(jComboBox1.getSelectedIndex() - 1) + "'");
                while (dbcon.rs.next()) {
                      dbcon2.rs = dbcon2.st.executeQuery("select id from symptoms_sub_sub where sub_id='" + dbcon.rs.getString(1)+ "'");
                      while (dbcon2.rs.next()) {
                 dbcon3.rs = dbcon3.st.executeQuery("select id from symptoms_sub_sub_sub where sub_id='" + dbcon2.rs.getString(1)+ "'");
                      while (dbcon3.rs.next()) {
                               dbcon4.rs = dbcon4.st.executeQuery("select id from symptoms_sub_sub_sub_sub where sub_id='" + dbcon3.rs.getString(1)+ "'");
                    while (dbcon4.rs.next()) {
                    dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub_sub_sub where sub_id=?");
                dbcon.ps.setString(1, dbcon4.rs.getString("id"));
                dbcon.ps.execute();
                }   
                    dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub_sub where sub_id=?");
                dbcon.ps.setString(1, dbcon3.rs.getString("id"));
                dbcon.ps.execute();
                }   
                dbcon.ps = dbcon2.con.prepareStatement("Delete from symptoms_sub_sub_sub_sub where sub_id=?");
                dbcon.ps.setString(1, dbcon2.rs.getString("id"));
                dbcon.ps.execute();
                }   
                 dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub where sub_id=?");
                dbcon.ps.setString(1, dbcon.rs.getString("id"));
                dbcon.ps.execute();
               
                }   
                   dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub where sym_id=?");
                dbcon.ps.setString(1, combo1.elementAt(jComboBox1.getSelectedIndex()- 1));
                dbcon.ps.execute();
                     dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms where id=?");
                dbcon.ps.setString(1, combo1.elementAt(jComboBox1.getSelectedIndex()- 1));
                dbcon.ps.execute();
            
              
            JOptionPane.showMessageDialog(rootPane, "done");
        } catch (Exception e) {
            e.printStackTrace();
        }   



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        combo2 = new Vector<>();
        if (jComboBox1.isFocusOwner()) {
            try {
                combomodel = new DefaultComboBoxModel();
                combomodel.addElement("select from below");
                dbcon.rs = dbcon.st.executeQuery("select id,name from symptoms_sub where sym_id='" + combo1.elementAt(jComboBox1.getSelectedIndex() - 1) + "'");
                while (dbcon.rs.next()) {
                    combomodel.addElement(dbcon.rs.getString(2));
                    combo2.addElement(dbcon.rs.getString(1));
                }
                jComboBox2.setModel(combomodel);
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        combo3 = new Vector<>();
        if (jComboBox2.isFocusOwner()) {
            try {
                combomodel = new DefaultComboBoxModel();
                combomodel.addElement("select from below");
                dbcon.rs = dbcon.st.executeQuery("select id,name from symptoms_sub_sub where sub_id='" + combo2.elementAt(jComboBox2.getSelectedIndex() - 1) + "'");
                while (dbcon.rs.next()) {
                    combomodel.addElement(dbcon.rs.getString(2));
                    combo3.addElement(dbcon.rs.getString(1));
                }
                jComboBox3.setModel(combomodel);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        combo4 = new Vector<>();
        if (jComboBox3.isFocusOwner()) {
            try {
                combomodel = new DefaultComboBoxModel();
                combomodel.addElement("select from below");
                dbcon.rs = dbcon.st.executeQuery("select id,name from symptoms_sub_sub_sub where sub_id='" + combo3.elementAt(jComboBox3.getSelectedIndex() - 1) + "'");
                while (dbcon.rs.next()) {
                    combomodel.addElement(dbcon.rs.getString(2));
                    combo4.addElement(dbcon.rs.getString(1));
                }
                jComboBox4.setModel(combomodel);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
   combo6= new Vector<>();
        if (jComboBox5.isFocusOwner()) {
            try {
                combomodel = new DefaultComboBoxModel();
                combomodel.addElement("select from below");
                dbcon.rs = dbcon.st.executeQuery("select id,name from symptoms_sub_sub_sub_sub_sub where sub_id='" + combo5.elementAt(jComboBox5.getSelectedIndex() - 1) + "'");
                while (dbcon.rs.next()) {
                    combomodel.addElement(dbcon.rs.getString(2));
                    combo6.addElement(dbcon.rs.getString(1));
                }
                jComboBox6.setModel(combomodel);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }        
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        combo5 = new Vector<>();
        if (jComboBox4.isFocusOwner()) {
            try {
                combomodel = new DefaultComboBoxModel();
                combomodel.addElement("select from below");
                dbcon.rs = dbcon.st.executeQuery("select id,name from symptoms_sub_sub_sub_sub where sub_id='" + combo4.elementAt(jComboBox4.getSelectedIndex() - 1) + "'");
                while (dbcon.rs.next()) {
                    combomodel.addElement(dbcon.rs.getString(2));
                    combo5.addElement(dbcon.rs.getString(1));
                }
                jComboBox5.setModel(combomodel);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);    
        setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
//  combo6= new Vector<>();
//        if (jComboBox4.isFocusOwner()) {
//            try {
//                combomodel = new DefaultComboBoxModel();
//                combomodel.addElement("select from below");
//                dbcon.rs = dbcon.st.executeQuery("select id,name from symptoms_sub_sub_sub_sub_sub where sub_id='" + combo5.elementAt(jComboBox5.getSelectedIndex() - 1) + "'");
//                while (dbcon.rs.next()) {
//                    combomodel.addElement(dbcon.rs.getString(2));
//                    combo6.addElement(dbcon.rs.getString(1));
//                }
//                jComboBox6.setModel(combomodel);
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }        

// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try {
              dbcon.rs = dbcon.st.executeQuery("select id from symptoms_sub_sub where sub_id='" + combo2.elementAt(jComboBox2.getSelectedIndex() - 1) + "'");
                while (dbcon.rs.next()) {
                      dbcon2.rs = dbcon2.st.executeQuery("select id from symptoms_sub_sub_sub where sub_id='" + dbcon.rs.getString(1)+ "'");
                      while (dbcon2.rs.next()) {
                 dbcon3.rs = dbcon3.st.executeQuery("select id from symptoms_sub_sub_sub_sub where sub_id='" + dbcon2.rs.getString(1)+ "'");
                      while (dbcon3.rs.next()) {
                    dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub_sub_sub where sub_id=?");
                dbcon.ps.setString(1, dbcon3.rs.getString("id"));
                dbcon.ps.execute();
                }   
                dbcon.ps = dbcon2.con.prepareStatement("Delete from symptoms_sub_sub_sub_sub where sub_id=?");
                dbcon.ps.setString(1, dbcon2.rs.getString("id"));
                dbcon.ps.execute();
                }   
                 dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub where sub_id=?");
                dbcon.ps.setString(1, dbcon.rs.getString("id"));
                dbcon.ps.execute();
               
                }   
                   dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub where sub_id=?");
                dbcon.ps.setString(1, combo2.elementAt(jComboBox2.getSelectedIndex()- 1));
                dbcon.ps.execute();
                     dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub where  id=?");
                dbcon.ps.setString(1, combo2.elementAt(jComboBox2.getSelectedIndex()- 1));
                dbcon.ps.execute();
            
              
            JOptionPane.showMessageDialog(rootPane, "done");
        } catch (Exception e) {
            e.printStackTrace();
        }   
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 try {
              dbcon.rs = dbcon.st.executeQuery("select id from symptoms_sub_sub_sub where sub_id='" + combo3.elementAt(jComboBox3.getSelectedIndex() - 1) + "'");
                while (dbcon.rs.next()) {
                      dbcon2.rs = dbcon2.st.executeQuery("select id from symptoms_sub_sub_sub_sub where sub_id='" + dbcon.rs.getString(1)+ "'");
                      while (dbcon2.rs.next()) {
                    dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub_sub_sub where sub_id=?");
                dbcon.ps.setString(1, dbcon2.rs.getString("id"));
                dbcon.ps.execute();
                }  
                  dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub_sub where  sub_id=?");
                    dbcon.ps.setString(1, dbcon.rs.getString("id"));
                         dbcon.ps.execute();
              }   
                        dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub where sub_id=?");
                dbcon.ps.setString(1, combo3.elementAt(jComboBox3.getSelectedIndex()- 1));
                dbcon.ps.execute();
                     dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub where  id=?");
                dbcon.ps.setString(1, combo3.elementAt(jComboBox3.getSelectedIndex()- 1));
                dbcon.ps.execute();
            
              
            JOptionPane.showMessageDialog(rootPane, "done");
        } catch (Exception e) {
            e.printStackTrace();
        }   
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 try {
              dbcon.rs = dbcon.st.executeQuery("select id from symptoms_sub_sub_sub_sub where sub_id='" + combo4.elementAt(jComboBox4.getSelectedIndex() - 1) + "'");
                while (dbcon.rs.next()) {
                    dbcon.ps = dbcon2.con.prepareStatement("Delete from symptoms_sub_sub_sub_sub_sub where sub_id=?");
                dbcon.ps.setString(1, dbcon.rs.getString("id"));
                dbcon.ps.execute();
                }  
                                  dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub_sub where  sub_id=?");
                    dbcon.ps.setString(1, combo4.elementAt(jComboBox4.getSelectedIndex()- 1));
                         dbcon.ps.execute();
                     dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub where  id=?");
                dbcon.ps.setString(1, combo4.elementAt(jComboBox4.getSelectedIndex()- 1));
                dbcon.ps.execute();
            
              
            JOptionPane.showMessageDialog(rootPane, "done");
        } catch (Exception e) {
            e.printStackTrace();
        }    
        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try {
              dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub_sub_sub where sub_id=?");
                dbcon.ps.setString(1, combo5.elementAt(jComboBox5.getSelectedIndex()- 1));
                dbcon.ps.execute();
                     dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub_sub where  id=?");
                dbcon.ps.setString(1, combo5.elementAt(jComboBox5.getSelectedIndex()- 1));
                dbcon.ps.execute();
              JOptionPane.showMessageDialog(rootPane, "done");
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
                dbcon.ps = dbcon.con.prepareStatement("Delete from symptoms_sub_sub_sub_sub_sub where  id=?");
                dbcon.ps.setString(1, combo6.elementAt(jComboBox6.getSelectedIndex()- 1));
                dbcon.ps.execute();
            JOptionPane.showMessageDialog(rootPane, "done");
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

            try {
                dbcon.rs = dbcon.st.executeQuery("select id,name from symptoms where name like'"+jTextField1.getText()+"%'");
                while (dbcon.rs.next()) {
                jComboBox1.setSelectedItem(dbcon.rs.getString("name"));
                 jButton1ActionPerformed(null);
                }
           
            } catch (Exception e) {
                e.printStackTrace();
            }
            return;
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
if(evt.getKeyCode()==10){
    jButton8ActionPerformed(null);
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      try {
                dbcon.ps = dbcon.con.prepareStatement("Delete from illness where  id=?");
                dbcon.ps.setString(1, combo7.elementAt(jComboBox7.getSelectedIndex()- 1));
                dbcon.ps.execute();
            JOptionPane.showMessageDialog(rootPane, "done");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteSymptom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteSymptom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteSymptom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteSymptom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteSymptom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    public static javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    public static javax.swing.JComboBox jComboBox3;
    public static javax.swing.JComboBox jComboBox4;
    public static javax.swing.JComboBox jComboBox5;
    public static javax.swing.JComboBox jComboBox6;
    public static javax.swing.JComboBox jComboBox7;
    public static javax.swing.JComboBox jComboBox8;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables


    void loadCombo() {

            combo1 = new Vector<>();
            combo7 = new Vector<>();
            combomodel.addElement("select from below");
            try {
                dbcon.rs = dbcon.st.executeQuery("select id,name from symptoms");
                while (dbcon.rs.next()) {
                    combomodel.addElement(dbcon.rs.getString(2));
                    combo1.addElement(dbcon.rs.getString(1));
                }
                jComboBox1.setModel(combomodel);
            } catch (Exception e) {
                e.printStackTrace();
            }
            combomodel = new DefaultComboBoxModel();
               combomodel.addElement("select from below");
            try {
                dbcon.rs = dbcon.st.executeQuery("select id,name from illness");
                while (dbcon.rs.next()) {
                    combomodel.addElement(dbcon.rs.getString(2));
                    combo7.addElement(dbcon.rs.getString(1));
                }
                jComboBox7.setModel(combomodel);
            } catch (Exception e) {
                e.printStackTrace();
            }
            return;
        }
        
        
   
}
