/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addcontent;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tosyngy
 */
public class IllnessRelation extends javax.swing.JFrame {
DbConnect dbcon = new DbConnect();
    DefaultTableModel tb= new DefaultTableModel();
    /**
     * Creates new form SyptomsRelative
     */
    public IllnessRelation() {
        initComponents();
        
        fetch();
        fetch_tab();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel4.setText("illness");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 710, 240));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel1.setText("symptoms");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 265, -1, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 710, 240));

        jLabel7.setText("remove");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 279, 55, 23));

        jLabel8.setText("remove");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 557, 55, 17));

        jLabel11.setText("refresh");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 554, 55, 23));

        jLabel12.setText("refresh");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 279, 55, 23));

        jTabbedPane1.addTab("symptoms map diagnose", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable3MouseEntered(evt);
            }
        });
        jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable3KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel2.setText("symptoms");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jTable4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable4KeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jLabel3.setText("remove");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel6.setText("remove");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel9.setText("refresh");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setText("refresh");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel5.setText("illness");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(234, 234, 234)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("diagnose map illness", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      if(jTable1.getSelectedRow()>-1)
        fetch2(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased

        if(evt.getKeyCode()==10 && jTable1.getSelectedRow()!=-1){
    String id=jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
    int selected=jTable1.getSelectedRow();
    jTable1.clearSelection();
            System.out.println(jTable1.getValueAt(selected, 1).toString()); 
update(id,selected);
 refresh();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
if(evt.getKeyCode()==10 && jTable2.getSelectedRow()!=-1){
        String id=jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
         int selected=jTable2.getSelectedRow();
    jTable2.clearSelection();
update2(id,selected);
 refresh();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2KeyReleased

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
         if(jTable3.getSelectedRow()>-1)
        fetch_tab2(jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyReleased
if(evt.getKeyCode()==10 && jTable3.getSelectedRow()!=-1){
        String id=jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString();
         int selected=jTable3.getSelectedRow();
    jTable3.clearSelection();
update4(id,selected);
 refresh();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3KeyReleased

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable4MouseClicked

    private void jTable4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable4KeyReleased
                    if(evt.getKeyCode()==10 && jTable4.getSelectedRow()!=-1){
    String id=jTable4.getValueAt(jTable4.getSelectedRow(), 0).toString();
    int selected=jTable4.getSelectedRow();
    jTable4.clearSelection();
            System.out.println(jTable4.getValueAt(selected, 1).toString()); 
update3(id,selected);
 refresh();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable4KeyReleased

    private void jTable3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseEntered
void refresh(){
       fetch();
        fetch_tab();
        jTable2.setModel(new DefaultTableModel());
        jTable4.setModel(new DefaultTableModel());
}
void refresh2(){
           if(jTable1.getSelectedRow()>-1)
       fetch2(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                if(jTable3.getSelectedRow()>-1)
        fetch_tab2(jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString());
}
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
 refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
  refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
if(jTable3.getSelectedRow()>-1){
        int chk=JOptionPane.showConfirmDialog(rootPane, "are you sure?");
       if(chk!=0)
        return;
        try {     
            dbcon.ps=dbcon.con.prepareStatement("delete from  ill_map_symptoms where sym_id ='"+jTable3.getValueAt(jTable3.getSelectedRow(), 0)+"'");
            dbcon.ps.executeUpdate();
            dbcon.ps=dbcon.con.prepareStatement("delete from  symptoms where id ='"+jTable3.getValueAt(jTable3.getSelectedRow(), 0)+"'");
               dbcon.ps.executeUpdate();

                  JOptionPane.showMessageDialog(rootPane, "a deletion was perform under symptoms  on id" +jTable3.getValueAt(jTable3.getSelectedRow(), 0));
        } catch (Exception e) {
            e.printStackTrace();
        }
refresh();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
if(jTable4.getSelectedRow()>-1){
        int chk=JOptionPane.showConfirmDialog(rootPane, "are you sure?");
    if(chk!=0)
        return;
        try {
            dbcon.ps=dbcon.con.prepareStatement("delete from illness  where id ='"+jTable4.getValueAt(jTable4.getSelectedRow(), 0)+"'");
               dbcon.ps.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane, "a deletion was perform under illness  on id" +jTable4.getValueAt(jTable4.getSelectedRow(), 0));
        } catch (Exception e) {
            e.printStackTrace();
        }
refresh2();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
if(jTable1.getSelectedRow()>-1){
        int chk=JOptionPane.showConfirmDialog(rootPane, "are you sure?");
    if(chk!=0)
        return;
        try {
                        dbcon.ps=dbcon.con.prepareStatement("delete from ill_map_symptoms  where ill_id ='"+jTable1.getValueAt(jTable1.getSelectedRow(), 0)+"'");
            dbcon.ps.executeUpdate();
            dbcon.ps=dbcon.con.prepareStatement("delete from illness  where id ='"+jTable1.getValueAt(jTable1.getSelectedRow(), 0)+"'");
               dbcon.ps.executeUpdate();

                  JOptionPane.showMessageDialog(rootPane, "a deletion was perform under illness  on id" +jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        } catch (Exception e) {
            e.printStackTrace();
        }
refresh();
}        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
if(jTable2.getSelectedRow()>-1){
    int chk=JOptionPane.showConfirmDialog(rootPane, "are you sure?");
      if(chk!=0)
        return;
        try {
            dbcon.ps=dbcon.con.prepareStatement("delete from symptoms  where id ='"+jTable2.getValueAt(jTable2.getSelectedRow(), 0)+"'");
            dbcon.ps.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane, "a deletion was perform under symptoms  on id" +jTable2.getValueAt(jTable2.getSelectedRow(), 0));
        } catch (Exception e) {
            e.printStackTrace();
        }
refresh2();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
      refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
 refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IllnessRelation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IllnessRelation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IllnessRelation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IllnessRelation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IllnessRelation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables

    private void fetch() {
             tb= new DefaultTableModel();
        tb.addColumn("id");
        tb.addColumn("Name");
        tb.addColumn("Description");
            try {
                dbcon.rs = dbcon.st.executeQuery("select id,name,description from illness order by name");
                while (dbcon.rs.next()) {
                Object ob[] = new Object[]{dbcon.rs.getString("id"),dbcon.rs.getString("name"),dbcon.rs.getString(3)};
                tb.addRow(ob);
                }
               jTable1.setModel(tb);
            } catch (Exception e) {
                e.printStackTrace();
            }
        
    }

    private void fetch_tab() {
         tb= new DefaultTableModel();
        tb.addColumn("id");
        tb.addColumn("name");
        tb.addColumn("body location");
            try {
                dbcon.rs = dbcon.st.executeQuery("select symptoms.id,symptoms.name,symptoms.body_location from symptoms order by name");
                while (dbcon.rs.next()) {
                Object ob[] = new Object[]{dbcon.rs.getString("id"),dbcon.rs.getString("name"),dbcon.rs.getString(3)};
                tb.addRow(ob);
                }
               jTable3.setModel(tb);
            } catch (Exception e) {
                e.printStackTrace();
            }
        
    }

    private void fetch_tab2(String id) {
         tb= new DefaultTableModel();
        tb.addColumn("id");
        tb.addColumn("name");
        tb.addColumn("body location");
            try {
                dbcon.rs = dbcon.st.executeQuery("select DISTINCT illness.id,illness.name,illness.description from illness,ill_map_symptoms where ill_map_symptoms.sym_id='"+id+"'  and  ill_map_symptoms.ill_id=illness.id order by name");
                while (dbcon.rs.next()) {
                Object ob[] = new Object[]{dbcon.rs.getString("illness.id"),dbcon.rs.getString("illness.name"),dbcon.rs.getString("illness.description")};
                tb.addRow(ob);
                }
               jTable4.setModel(tb);
            } catch (Exception e) {
                e.printStackTrace();
            }
        
    }
    private void fetch2(String id) {
         tb= new DefaultTableModel();
        tb.addColumn("id");
        tb.addColumn("name");
        tb.addColumn("body location");
            try {
                dbcon.rs = dbcon.st.executeQuery("select DISTINCT symptoms.id,symptoms.name,symptoms.body_location from symptoms,ill_map_symptoms where ill_map_symptoms.ill_id='"+id+"'  and  ill_map_symptoms.sym_id=symptoms.id order by name");
                while (dbcon.rs.next()) {
                Object ob[] = new Object[]{dbcon.rs.getString("symptoms.id"),dbcon.rs.getString("symptoms.name"),dbcon.rs.getString("symptoms.body_location")};
                tb.addRow(ob);
                }
               jTable2.setModel(tb);
            } catch (Exception e) {
                e.printStackTrace();
            }
        
    }

 

    private void update(String id,int sel) {
        try {
            dbcon.ps=dbcon.con.prepareStatement("update illness set name=?,description=? where id ='"+id+"'");
            dbcon.ps.setString(1,jTable1.getModel().getValueAt(sel, 1).toString());
            dbcon.ps.setString(2,jTable1.getModel().getValueAt(sel, 2).toString());
            dbcon.ps.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane, "an update was perform under illness  on id" +id);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void update2(String id,int sel) {
        try {
            dbcon.ps=dbcon.con.prepareStatement("update symptoms set name=?,body_location=?  where id ='"+id+"'");
            dbcon.ps.setString(1,jTable2.getModel().getValueAt(sel, 1).toString());
            dbcon.ps.setString(2,jTable2.getModel().getValueAt(sel, 2).toString());
            dbcon.ps.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane, "an update was perform under symptoms on id" +id);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void update3(String id,int sel) {
        try {
            dbcon.ps=dbcon.con.prepareStatement("update illness set name=?,description=? where id ='"+id+"'");
            dbcon.ps.setString(1,jTable4.getModel().getValueAt(sel, 1).toString());
            dbcon.ps.setString(2,jTable4.getModel().getValueAt(sel, 2).toString());
            dbcon.ps.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane, "an update was perform under illness  on id" +id);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void update4(String id,int sel) {
        try {
            dbcon.ps=dbcon.con.prepareStatement("update symptoms set name=?,body_location=?  where id ='"+id+"'");
            dbcon.ps.setString(1,jTable3.getModel().getValueAt(sel, 1).toString());
            dbcon.ps.setString(2,jTable3.getModel().getValueAt(sel, 2).toString());
            dbcon.ps.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane, "an update was perform under symptoms on id" +id);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
