package addcontent;

import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tosyngy
 */
public class illness extends javax.swing.JFrame {
    DefaultComboBoxModel combomodel = new DefaultComboBoxModel();
    DbConnect dbcon = new DbConnect();
    Vector<String> combo1;
    Vector<String> combo2;
    Vector<String> combo3;
    Vector<String> combo4;
    Vector<String> lst1 =new Vector<>();
    Vector<String> lst2=new Vector<>();
    DefaultListModel list=new DefaultListModel();
    DefaultListModel list2=new DefaultListModel();
    /**
     * Creates new form illness
     */
    public  static int i;
    public illness() {
        initComponents();
        loadOn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 220, 50));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 190, 100));

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 70, 30));

        jLabel4.setText("illness");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 40));

        jLabel3.setText("symptoms");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 40));

        jScrollPane3.setViewportView(jList1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 250));

        jTabbedPane1.addTab("symptoms to illness", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 220, 50));

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jComboBox4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox4KeyReleased(evt);
            }
        });
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 220, 50));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 190, 100));

        jButton2.setText("save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 70, 40));

        jLabel5.setText("illness");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 40));

        jLabel6.setText("symptoms");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 40));

        jScrollPane4.setViewportView(jList2);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 250));

        jTabbedPane1.addTab("illness to symptoms", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     if(jComboBox1.getSelectedIndex()>0)
        combo1.elementAt(jComboBox1.getSelectedIndex() - 1) ;
      
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
      if(jComboBox2.getSelectedIndex()>0)
        combo2.elementAt(jComboBox2.getSelectedIndex() - 1) ;
   // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if (lst1.isEmpty()|| jComboBox1.getSelectedIndex() == 0) {
                    jComboBox1.requestFocus();
                    return;
                }
         try{
             for(int i=0;i<lst1.size();i++){
                             dbcon.rs = dbcon.st.executeQuery("select id from ill_map_symptoms where `ill_id`='"+combo1.elementAt(jComboBox1.getSelectedIndex() - 1) +"' and  `sym_id`='"+lst1.elementAt(i)+"'");
            if (dbcon.rs.next()) {
                JOptionPane.showMessageDialog(rootPane,jComboBox3.getSelectedItem().toString()+"=>"+ jList2.getSelectedValue()+" already");
            continue;
            }
                  dbcon.ps = dbcon.con.prepareStatement("INSERT INTO `diagnosis`.`ill_map_symptoms` (`sym_id`,  `ill_id`, `description`) VALUES ( ?,?,?)");
                dbcon.ps.setString(1, combo1.elementAt(jComboBox1.getSelectedIndex() - 1) );
                dbcon.ps.setString(2, lst1.elementAt(i));
                dbcon.ps.setString(3, jTextArea1.getText());
                dbcon.ps.execute();   
             }
           
         } catch (Exception e) {
            e.printStackTrace();
        }
           JOptionPane.showMessageDialog(rootPane, "done");
              jList1.setModel(list=new DefaultListModel());
         lst1=new Vector<>();
         jComboBox2.requestFocus();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
      if(jComboBox3.getSelectedIndex()>0)
        combo3.elementAt(jComboBox3.getSelectedIndex() - 1) ;
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
   if(jComboBox4.getSelectedIndex()>0)
        combo4.elementAt(jComboBox4.getSelectedIndex() - 1) ;
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if (lst2.isEmpty() || jComboBox3.getSelectedIndex() == 0) {
                    jComboBox3.requestFocus();
                    return;
                }
       for(int i=0;i<lst2.size();i++){
            try{
                      dbcon.rs = dbcon.st.executeQuery("select id from ill_map_symptoms where `ill_id`='"+lst2.elementAt(i)+"' and  `sym_id`='"+ combo3.elementAt(jComboBox3.getSelectedIndex() - 1) +"'");
            if (dbcon.rs.next()) {
                JOptionPane.showMessageDialog(rootPane,jComboBox3.getSelectedItem().toString()+"=>"+ jList2.getSelectedValue()+" already");
            continue;
            }
                
                dbcon.ps = dbcon.con.prepareStatement("INSERT INTO `diagnosis`.`ill_map_symptoms` (`ill_id`,`sym_id`,   `description`) VALUES ( ?,?,?)");
                dbcon.ps.setString(1, combo3.elementAt(jComboBox3.getSelectedIndex() - 1) );
                dbcon.ps.setString(2,lst2.elementAt(i));
                dbcon.ps.setString(3, jTextArea2.getText());
                dbcon.ps.execute();   
         } catch (Exception e) {
            e.printStackTrace();
        }
       }
    
           JOptionPane.showMessageDialog(rootPane, "done");
         jComboBox4.requestFocus();
          jList2.setModel(list2=new DefaultListModel());
         lst2=new Vector<>();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
  if(evt.getKeyCode()==10){
      if(list.contains(jComboBox2.getSelectedItem().toString()))
          return;
  list.addElement(jComboBox2.getSelectedItem().toString());
 lst1.addElement(combo2.elementAt(jComboBox2.getSelectedIndex() - 1));
   jList1.setModel(list);
  }
  

    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jComboBox4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4KeyReleased

    private void jComboBox4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox4KeyPressed
  if(evt.getKeyCode()==10){
          if(list2.contains(jComboBox4.getSelectedItem().toString()))
          return;
  list2.addElement(jComboBox4.getSelectedItem().toString());
 lst2.addElement(combo4.elementAt(jComboBox4.getSelectedIndex() - 1));
  }
  jList2.setModel(list2);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(illness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(illness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(illness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(illness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new illness().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    public static javax.swing.JComboBox jComboBox3;
    public static javax.swing.JComboBox jComboBox4;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
public void loadOn(){
     combo1 = new Vector<>();
        combo2 = new Vector<>();
        combo3 = new Vector<>();
        combo4 = new Vector<>();
        combomodel.addElement("select from below");
        try {
            dbcon.rs = dbcon.st.executeQuery("select id,name from symptoms order by name");
            while (dbcon.rs.next()) {
                combomodel.addElement(dbcon.rs.getString(2));
                combo1.addElement(dbcon.rs.getString(1));
                combo4.addElement(dbcon.rs.getString(1));
            }
            jComboBox1.setModel(combomodel);
            jComboBox4.setModel(combomodel);

            combomodel = new DefaultComboBoxModel();
            combomodel.addElement("select from below");
            dbcon.rs = dbcon.st.executeQuery("select id,name from illness order by name");
            while (dbcon.rs.next()) {
                combomodel.addElement(dbcon.rs.getString(2));
                combo2.addElement(dbcon.rs.getString(1));
                combo3.addElement(dbcon.rs.getString(1));
            }
            jComboBox2.setModel(combomodel);
            jComboBox3.setModel(combomodel);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
