/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addcontent;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tosyngy
 */
public class Syptoms_map extends javax.swing.JFrame {
DbConnect dbcon = new DbConnect();
    DefaultTableModel tb= new DefaultTableModel();
    /**
     * Creates new form SyptomsRelative
     */
    public Syptoms_map() {
        initComponents();
        fetch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 560, 240));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable3KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 470, 230));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jTable4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable4KeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jTable4);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 330, 230));

        jLabel1.setText("sub 1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, -1, -1));

        jLabel2.setText("sub 2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, 30));

        jLabel3.setText("sub 3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, -1));

        jLabel4.setText("symptoms");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 640, 240));

        jLabel5.setText("sub 4");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, -1, 20));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jTable5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable5KeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(jTable5);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 390, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1327, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
      if(jTable4.getSelectedRow()>-1)
        fetch5(jTable4.getValueAt(jTable4.getSelectedRow(), 0).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable4MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      if(jTable1.getSelectedRow()>-1)
        fetch2(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
  if(jTable2.getSelectedRow()>-1)
        fetch3(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
      if(jTable3.getSelectedRow()>-1)
        fetch4(jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased

        if(evt.getKeyCode()==10 && jTable1.getSelectedRow()!=-1){
    String id=jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
    int selected=jTable1.getSelectedRow();
    jTable1.clearSelection();
            System.out.println(jTable1.getValueAt(selected, 1).toString()); 
update(id,selected);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
if(evt.getKeyCode()==10 && jTable2.getSelectedRow()!=-1){
        String id=jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
         int selected=jTable2.getSelectedRow();
    jTable2.clearSelection();
update2(id,selected);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2KeyReleased

    private void jTable3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyReleased
if(evt.getKeyCode()==10 && jTable3.getSelectedRow()!=-1){
           String id=jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString();
            int selected=jTable3.getSelectedRow();
    jTable3.clearSelection();
update3(id,selected);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3KeyReleased

    private void jTable4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable4KeyReleased
if(evt.getKeyCode()==10 && jTable4.getSelectedRow()!=-1){
                String id=jTable4.getValueAt(jTable4.getSelectedRow(), 0).toString();
                 int selected=jTable4.getSelectedRow();
    jTable4.clearSelection();
update4(id,selected);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable4KeyReleased

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable5MouseClicked

    private void jTable5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable5KeyReleased
if(evt.getKeyCode()==10 && jTable5.getSelectedRow()!=-1){
                String id=jTable5.getValueAt(jTable5.getSelectedRow(), 0).toString();
                 int selected=jTable5.getSelectedRow();
    jTable5.clearSelection();
update5(id,selected);
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_jTable5KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Syptoms_map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Syptoms_map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Syptoms_map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Syptoms_map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Syptoms_map().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables

    private void fetch() {
        tb.addColumn("id");
        tb.addColumn("Name");
        tb.addColumn("description");
        tb.addColumn("Location");
            try {
                dbcon.rs = dbcon.st.executeQuery("select id,name,body_location,description from symptoms order by name");
                while (dbcon.rs.next()) {
                Object ob[] = new Object[]{dbcon.rs.getString("id"),dbcon.rs.getString("name"),dbcon.rs.getString("description"),dbcon.rs.getString(3)};
                tb.addRow(ob);
                }
               jTable1.setModel(tb);
            } catch (Exception e) {
                e.printStackTrace();
            }
        
    }

    private void fetch2(String id) {
         tb= new DefaultTableModel();
        tb.addColumn("id");
        tb.addColumn("symid");
        tb.addColumn("name");
        tb.addColumn("description");
        tb.addColumn("stage");
            try {
                dbcon.rs = dbcon.st.executeQuery("select id,sym_id,name,stage,description from symptoms_sub where sym_id='"+id+"' order by name");
                while (dbcon.rs.next()) {
                Object ob[] = new Object[]{dbcon.rs.getString("id"),dbcon.rs.getString("sym_id"),dbcon.rs.getString("name"),dbcon.rs.getString("description"),dbcon.rs.getString("stage")};
                tb.addRow(ob);
                }
               jTable2.setModel(tb);
            } catch (Exception e) {
                e.printStackTrace();
            }
        
    }
    private void fetch3(String id) {
         tb= new DefaultTableModel();
        tb.addColumn("id");
        tb.addColumn("symid");
        tb.addColumn("name");
        tb.addColumn("description");
        tb.addColumn("stage");
            try {
                dbcon.rs = dbcon.st.executeQuery("select id,sub_id,name,stage,description from symptoms_sub_sub where sub_id='"+id+"' order by name");
                while (dbcon.rs.next()) {
                Object ob[] = new Object[]{dbcon.rs.getString("id"),dbcon.rs.getString("sub_id"),dbcon.rs.getString("name"),dbcon.rs.getString("description"),dbcon.rs.getString("stage")};
                tb.addRow(ob);
                }
               jTable3.setModel(tb);
            } catch (Exception e) {
                e.printStackTrace();
            }
        
    }
    private void fetch4(String id) {
         tb= new DefaultTableModel();
        tb.addColumn("id");
        tb.addColumn("symid");
        tb.addColumn("name");
        tb.addColumn("Description");
        tb.addColumn("stage");
            try {
                dbcon.rs = dbcon.st.executeQuery("select id,sub_id,name,stage,description from symptoms_sub_sub_sub where sub_id='"+id+"' order by name");
                while (dbcon.rs.next()) {
                Object ob[] = new Object[]{dbcon.rs.getString("id"),dbcon.rs.getString("sub_id"),dbcon.rs.getString("name"),dbcon.rs.getString("description"),dbcon.rs.getString("stage")};
                tb.addRow(ob);
                }
               jTable4.setModel(tb);
            } catch (Exception e) {
                e.printStackTrace();
            }
        
    }
    private void fetch5 (String id) {
         tb= new DefaultTableModel();
        tb.addColumn("id");
        tb.addColumn("symid");
        tb.addColumn("name");
        tb.addColumn("description");
        tb.addColumn("stage");
            try {
                dbcon.rs = dbcon.st.executeQuery("select id,sub_id,name,stage,description from symptoms_sub_sub_sub_sub where sub_id='"+id+"' order by name");
                while (dbcon.rs.next()) {
                Object ob[] = new Object[]{dbcon.rs.getString("id"),dbcon.rs.getString("sub_id"),dbcon.rs.getString("name"),dbcon.rs.getString("description"),dbcon.rs.getString("stage")};
                tb.addRow(ob);
                }
               jTable5.setModel(tb);
            } catch (Exception e) {
                e.printStackTrace();
            }
        
    }

    private void update(String id,int sel) {
        try {
            dbcon.ps=dbcon.con.prepareStatement("update symptoms set name=?,body_location=? where id ='"+id+"'");
            dbcon.ps.setString(1,jTable1.getModel().getValueAt(sel, 1).toString());
            dbcon.ps.setString(2,jTable1.getModel().getValueAt(sel, 2).toString());
            dbcon.ps.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane, "an update was perform under symptoms  on id" +id);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void update2(String id,int sel) {
        try {
            dbcon.ps=dbcon.con.prepareStatement("update symptoms_sub set name=?,sym_id=?,stage=?  where id ='"+id+"'");
            dbcon.ps.setString(1,jTable2.getModel().getValueAt(sel, 2).toString());
            dbcon.ps.setString(2,jTable2.getModel().getValueAt(sel, 1).toString());
            dbcon.ps.setString(3,jTable2.getModel().getValueAt(sel, 4).toString());
            dbcon.ps.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane, "an update was perform under sub 1 on id" +id);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void update3(String id,int sel) {
        try {
            dbcon.ps=dbcon.con.prepareStatement("update symptoms_sub_sub set name=?,sub_id=?,stage=? where  id ='"+id+"'");
            dbcon.ps.setString(1,jTable3.getModel().getValueAt(sel, 2).toString());
            dbcon.ps.setString(2,jTable3.getModel().getValueAt(sel, 1).toString());
            dbcon.ps.setString(3,jTable3.getModel().getValueAt(sel, 4).toString());
                  JOptionPane.showMessageDialog(rootPane, "an update was perform under sub 2 on id" +id);
                  dbcon.ps.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void update4(String id,int sel) {
        try {
            dbcon.ps=dbcon.con.prepareStatement("update symptoms_sub_sub_sub set name=?,sub_id=?,stage=?  where id ='"+id+"'");
            dbcon.ps.setString(1,jTable4.getModel().getValueAt(sel, 2).toString());
            dbcon.ps.setString(2,jTable4.getModel().getValueAt(sel, 1).toString());
            dbcon.ps.setString(3,jTable4.getModel().getValueAt(sel, 4).toString());
            dbcon.ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "an update was perform under sub 3 on id" +id);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void update5(String id,int sel) {
        try {
            dbcon.ps=dbcon.con.prepareStatement("update symptoms_sub_sub_sub_sub set name=?,sub_id=?,stage=?  where id ='"+id+"'");
            dbcon.ps.setString(1,jTable4.getModel().getValueAt(sel, 2).toString());
            dbcon.ps.setString(2,jTable4.getModel().getValueAt(sel, 1).toString());
            dbcon.ps.setString(3,jTable4.getModel().getValueAt(sel, 4).toString());
            dbcon.ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "an update was perform under sub 4 on id" +id);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
